version: '3'

services:
  tg-sleepwatch:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}